function appInitPictogramTypes()
    appAddPictogramType('015-circle', 'shapes')
    appAddPictogramType('016-square', 'shapes')
    appAddPictogramType('017-diamond', 'shapes')
    appAddPictogramType('018-triangle-up', 'shapes')
    appAddPictogramType('019-triangle-down', 'shapes')

    appAddPictogramType('001-me', 'personal', {isPermanentSticky = true, isPersonalPronoun = true})
    appAddPictogramType('002-you', 'personal', {isPermanentSticky = true, isPersonalPronoun = true})
    appAddPictogramType('136-speak', 'shapes')
    appAddPictogramType('137-think', 'shapes', {isPermanentSticky = true})
    appAddPictogramType('003-a-he-or-she', 'personal', {isPersonalPronoun = true})
    appAddPictogramType('003-b-them', 'personal', {isPersonalPronoun = true})
    appAddPictogramType('004-us', 'personal', {isPersonalPronoun = true})
    appAddPictogramType('005-son', 'personal')
    appAddPictogramType('006-daughter', 'personal')
    appAddPictogramType('007-boyfriend', 'personal')
    appAddPictogramType('008-girlfriend', 'personal')
    appAddPictogramType('009-love', 'personal', {isPermanentSticky = true, isConnector = true})
    appAddPictogramType('010-hate', 'personal', {isPermanentSticky = true, isConnector = true})
    appAddPictogramType('011-split-apart', 'personal')
    appAddPictogramType('012-girl', 'personal')
    appAddPictogramType('013-boy', 'personal')
    appAddPictogramType('014-kid', 'personal')
    appAddPictogramType('015-married', 'personal')
    appAddPictogramType('016-left-pointer', 'personal', {isPermanentSticky = true, isConnector = true})
    appAddPictogramType('017-right-pointer', 'personal', {isPermanentSticky = true, isConnector = true})
    appAddPictogramType('018-left-right-pointer', 'personal', {isPermanentSticky = true})
    appAddPictogramType('019-not-left-pointer', 'personal')
    appAddPictogramType('020-not-right-pointer', 'personal')
    appAddPictogramType('021-like', 'personal')
    appAddPictogramType('022-dislike', 'personal')
    appAddPictogramType('024-person', 'personal')
    appAddPictogramType('025-persons', 'personal')
    appAddPictogramType('026-pony-tail', 'personal')
    appAddPictogramType('027-ear', 'personal')
    appAddPictogramType('028-eye', 'personal')
    appAddPictogramType('029-neck', 'personal')
    appAddPictogramType('030-arm', 'personal')
    appAddPictogramType('031-hand', 'personal')
    appAddPictogramType('032-foot', 'personal')
    appAddPictogramType('033-finger', 'personal')
    appAddPictogramType('052-male-breast', 'personal')
    appAddPictogramType('059-elbow', 'personal')
    appAddPictogramType('056-toe', 'personal')

    appAddPictogramType('056-hair', 'personal')
    appAddPictogramType('052-goatee', 'personal')
    appAddPictogramType('053-beard', 'personal')
    appAddPictogramType('054-moustache', 'personal')
    appAddPictogramType('055-bald', 'personal')
    appAddPictogramType('057-bottom-beard', 'personal')
    appAddPictogramType('058-long-hair', 'personal')
    appAddPictogramType('059-short-hair', 'personal')

    appAddPictogramType('054-butt', 'personal')
    appAddPictogramType('055-belly', 'personal')
    appAddPictogramType('057-mouth', 'personal')

    appAddPictogramType('058-teeth', 'personal')
    appAddPictogramType('061-eyebrow', 'personal')
    appAddPictogramType('062-nostril', 'personal')
    appAddPictogramType('063-cheeks', 'personal')
    appAddPictogramType('064-ear-ring', 'personal')
    appAddPictogramType('065-brain', 'personal')
    appAddPictogramType('066-heart', 'personal')
    appAddPictogramType('067-stomach', 'personal')
    appAddPictogramType('068-lungs', 'personal')
    appAddPictogramType('069-injury', 'personal')
    appAddPictogramType('070-nail', 'personal')
    appAddPictogramType('001-run', 'verbs')
    appAddPictogramType('002-sit', 'verbs')
    appAddPictogramType('003-punch', 'verbs')
    appAddPictogramType('004-press', 'verbs')
    appAddPictogramType('005-lift', 'verbs')
    appAddPictogramType('006-jump', 'verbs')
    appAddPictogramType('007-a-give', 'verbs')

    appAddPictogramType('089-drink', 'verbs')
    appAddPictogramType('092-touch', 'verbs')
    appAddPictogramType('108-have', 'verbs')
    appAddPictogramType('095-hold', 'verbs')
    appAddPictogramType('096-lose', 'verbs')

    appAddPictogramType('007-b-fly', 'verbs')
    appAddPictogramType('010-look', 'verbs')
    appAddPictogramType('011-listen', 'verbs')

    appAddPictogramType('013-kiss', 'verbs')
    appAddPictogramType('014-punch', 'verbs')
    appAddPictogramType('015-laugh', 'verbs')
    appAddPictogramType('016-spit', 'verbs')
    appAddPictogramType('017-wink', 'verbs')

    appAddPictogramType('012-speak', 'verbs')
    appAddPictogramType('speak-b', 'verbs')

    appAddPictogramType('018-throw', 'verbs')
    appAddPictogramType('019-shout', 'verbs')
    appAddPictogramType('020-sing', 'verbs')
    appAddPictogramType('021-read', 'verbs')
    appAddPictogramType('022-type', 'verbs')
    appAddPictogramType('023-write', 'verbs')
    appAddPictogramType('024-draw', 'verbs')
    appAddPictogramType('008-aim', 'verbs')
    appAddPictogramType('009-shoot', 'verbs')
    appAddPictogramType('025-set-on-fire', 'verbs')
    appAddPictogramType('026-water', 'verbs')
    appAddPictogramType('027-protest-or-advertise', 'verbs')
    appAddPictogramType('028-stumble-or-fall', 'verbs')
    appAddPictogramType('029-understand', 'verbs')
    appAddPictogramType('030-pay', 'verbs')
    appAddPictogramType('031-get-paid', 'verbs')
    appAddPictogramType('032-photograph', 'verbs')
    appAddPictogramType('033-calculate', 'verbs')
    appAddPictogramType('034-think', 'verbs')
    appAddPictogramType('think-b', 'verbs')
    appAddPictogramType('035-sleep', 'verbs')
    appAddPictogramType('036-shower', 'verbs')
    appAddPictogramType('037-love', 'verbs')
    appAddPictogramType('038-hate', 'verbs')
    appAddPictogramType('039-build-or-hammer', 'verbs')
    appAddPictogramType('040-search', 'verbs')
    appAddPictogramType('041-show-off', 'verbs')
    appAddPictogramType('042-film', 'verbs')
    appAddPictogramType('043-act', 'verbs')
    appAddPictogramType('044-waste-money', 'verbs')
    appAddPictogramType('045-save-money', 'verbs')
    appAddPictogramType('046-paint-face', 'verbs')
    appAddPictogramType('047-make-music', 'verbs')
    appAddPictogramType('048-swim', 'verbs')
    appAddPictogramType('049-destroy', 'verbs')
    appAddPictogramType('050-watch-or-peek', 'verbs')
    appAddPictogramType('051-jump-off', 'verbs')
    appAddPictogramType('052-kill', 'verbs')
    appAddPictogramType('053-close-eyes', 'verbs')
    appAddPictogramType('054-open', 'verbs')
    appAddPictogramType('055-close', 'verbs')
    appAddPictogramType('056-discover', 'verbs')
    appAddPictogramType('057-cooking', 'verbs')
    appAddPictogramType('059-walking', 'verbs')
    appAddPictogramType('060-blowing', 'verbs')
    appAddPictogramType('061-announcing', 'verbs')
    appAddPictogramType('062-pointing', 'verbs')
    appAddPictogramType('063-eating', 'verbs')
    appAddPictogramType('064-self-inspection', 'verbs')
    appAddPictogramType('065-give-kid', 'verbs')
    appAddPictogramType('066-sitting', 'verbs')
    appAddPictogramType('067-chat', 'verbs')
    appAddPictogramType('068-applauding', 'verbs')
    appAddPictogramType('069-plan', 'verbs')
    appAddPictogramType('070-painting', 'verbs')
    appAddPictogramType('071-teaching', 'verbs')
    appAddPictogramType('072-cleaning', 'verbs')
    appAddPictogramType('073-building', 'verbs')
    appAddPictogramType('074-removing', 'verbs')
    appAddPictogramType('075-reply', 'verbs')
    appAddPictogramType('076-reprimand', 'verbs')
    appAddPictogramType('077-agree', 'verbs')
    appAddPictogramType('078-disagree', 'verbs')
    appAddPictogramType('079-not-understand', 'verbs')
    appAddPictogramType('080-stealing', 'verbs')
    appAddPictogramType('081-complain', 'verbs')
    appAddPictogramType('082-attack', 'verbs')
    appAddPictogramType('083-ignore', 'verbs')
    appAddPictogramType('084-find-treasure', 'verbs')
    appAddPictogramType('085-lick', 'verbs')
    appAddPictogramType('086-magnify', 'verbs')
    appAddPictogramType('087-falling', 'verbs')
    appAddPictogramType('088-bumping', 'verbs')
    appAddPictogramType('093-marching', 'verbs')
    appAddPictogramType('094-cut', 'verbs')
    appAddPictogramType('097-public-or-outside', 'verbs')
    appAddPictogramType('098-private-or-inside', 'verbs')
    appAddPictogramType('099-fill', 'verbs')
    appAddPictogramType('100-break', 'verbs')
    appAddPictogramType('101-call', 'verbs')
    appAddPictogramType('102-call', 'verbs')
    appAddPictogramType('103-arrive', 'verbs')
    appAddPictogramType('104-leave', 'verbs')
    appAddPictogramType('105-dance', 'verbs')
    appAddPictogramType('106-hanging', 'verbs')
    appAddPictogramType('107-fight', 'verbs')
    appAddPictogramType('109-do', 'verbs')

    appAddPictogramType('001-tall', 'adjectives')
    appAddPictogramType('002-small', 'adjectives')
    appAddPictogramType('003-big', 'adjectives')
    appAddPictogramType('004-tiny', 'adjectives')
    appAddPictogramType('005-fast', 'adjectives')
    appAddPictogramType('006-slow', 'adjectives')
    appAddPictogramType('007-close', 'adjectives')
    appAddPictogramType('007-far', 'adjectives')
    appAddPictogramType('008-pretty', 'adjectives')
    appAddPictogramType('009-ugly', 'adjectives')
    appAddPictogramType('010-young', 'adjectives')
    appAddPictogramType('011-old', 'adjectives')
    appAddPictogramType('012-square', 'adjectives')
    appAddPictogramType('013-round', 'adjectives')
    appAddPictogramType('014-light', 'adjectives')
    appAddPictogramType('015-heavy', 'adjectives')
    appAddPictogramType('016-popular', 'adjectives')
    appAddPictogramType('017-lonely', 'adjectives')
    appAddPictogramType('074-medium-time', 'adjectives')
    appAddPictogramType('075-short-time', 'adjectives')
    appAddPictogramType('076-long-time', 'adjectives')
    appAddPictogramType('earlier', 'adjectives')
    appAddPictogramType('now', 'adjectives')
    appAddPictogramType('later', 'adjectives')
    appAddPictogramType('031-early', 'adjectives')
    appAddPictogramType('030-late', 'adjectives')
    appAddPictogramType('114-remember-or-forget', 'adjectives')
    appAddPictogramType('115-mine-own', 'adjectives')
    appAddPictogramType('116-shiny-new', 'adjectives')
    appAddPictogramType('018-smart', 'adjectives')
    appAddPictogramType('018-stupid', 'adjectives')
    appAddPictogramType('019-friendly', 'adjectives')
    appAddPictogramType('020-unfriendly', 'adjectives')
    appAddPictogramType('021-bright', 'adjectives')
    appAddPictogramType('022-dark', 'adjectives')
    appAddPictogramType('029-tired', 'adjectives')
    appAddPictogramType('024-expensive', 'adjectives')
    appAddPictogramType('025-cheap', 'adjectives')
    appAddPictogramType('026-free', 'adjectives')
    appAddPictogramType('023-good-smell', 'adjectives')
    appAddPictogramType('023-smelly', 'adjectives')
    appAddPictogramType('034-cute', 'adjectives')
    appAddPictogramType('027-fat', 'adjectives')
    appAddPictogramType('028-slim', 'adjectives')
    appAddPictogramType('032-quiet', 'adjectives')
    appAddPictogramType('033-loud', 'adjectives')
    appAddPictogramType('035-greedy', 'adjectives')
    appAddPictogramType('036-generous', 'adjectives')
    appAddPictogramType('037-rich', 'adjectives')
    appAddPictogramType('038-poor', 'adjectives')
    appAddPictogramType('039-dangerous', 'adjectives')
    appAddPictogramType('040-dead', 'adjectives')
    appAddPictogramType('041-honest', 'adjectives')
    appAddPictogramType('042-dishonest', 'adjectives')
    appAddPictogramType('043-strong', 'adjectives')
    appAddPictogramType('044-weak', 'adjectives')
    appAddPictogramType('045-hairy', 'adjectives')
    appAddPictogramType('046-non-hairy', 'adjectives')
    appAddPictogramType('047-painful', 'adjectives')
    appAddPictogramType('048-clean', 'adjectives')
    appAddPictogramType('049-dirty', 'adjectives')
    appAddPictogramType('050-broken', 'adjectives')
    appAddPictogramType('051-high', 'adjectives')
    appAddPictogramType('052-hungry', 'adjectives')
    appAddPictogramType('053-stuffed', 'adjectives')
    appAddPictogramType('063-desert', 'adjectives')
    appAddPictogramType('064-crowded-place', 'adjectives')
    appAddPictogramType('065-silent', 'adjectives')
    appAddPictogramType('066-pregnant', 'adjectives')
    appAddPictogramType('067-safe', 'adjectives')
    appAddPictogramType('068-dangerous', 'adjectives')
    appAddPictogramType('069-overpowered', 'adjectives')
    appAddPictogramType('070-wild', 'adjectives')
    appAddPictogramType('071-unequal', 'adjectives')
    appAddPictogramType('072-equal', 'adjectives', {isConnector = true})
    appAddPictogramType('073-comfy', 'adjectives')
    appAddPictogramType('077-blindfolded', 'adjectives')
    appAddPictogramType('078-unreachable', 'adjectives')
    appAddPictogramType('079-leaking', 'adjectives')
    appAddPictogramType('080-false', 'adjectives')
    appAddPictogramType('081-correct', 'adjectives')
    appAddPictogramType('082-cold', 'adjectives')
    appAddPictogramType('083-warm', 'adjectives')
    appAddPictogramType('084-challenging', 'adjectives')
    appAddPictogramType('085-skilled', 'adjectives')
    appAddPictogramType('086-hidden', 'adjectives')
    appAddPictogramType('087-complicated-thinking', 'adjectives')
    appAddPictogramType('088-simple-thinking', 'adjectives')
    appAddPictogramType('089-positive-thinking', 'adjectives')
    appAddPictogramType('090-negative-thinking', 'adjectives')
    appAddPictogramType('091-uniform-thinking', 'adjectives')
    appAddPictogramType('092-diverse-thinking', 'adjectives')
    appAddPictogramType('093-self-thinking', 'adjectives')
    appAddPictogramType('094-thinking', 'adjectives')
    appAddPictogramType('095-thinking', 'adjectives')
    appAddPictogramType('096-stressed-thinking', 'adjectives')
    appAddPictogramType('097-love-thinking', 'adjectives')
    appAddPictogramType('098-focused-thinking', 'adjectives')
    appAddPictogramType('099-unfocused-thinking', 'adjectives')
    appAddPictogramType('100-optimistic-thinking', 'adjectives')
    appAddPictogramType('101-pessimistic-thinking', 'adjectives')
    appAddPictogramType('102-b-know', 'adjectives')
    appAddPictogramType('110-freestyle-thinking', 'adjectives')
    appAddPictogramType('111-freestyle-thinking', 'adjectives')
    appAddPictogramType('112-freestyle-thinking', 'adjectives')
    appAddPictogramType('113-freestyle-thinking', 'adjectives')

    appAddPictogramType('001-happy', 'emoticons', {isPermanentSticky = true, isEmoticon = true})
    appAddPictogramType('002-unhappy', 'emoticons', {isPermanentSticky = true})
    appAddPictogramType('003-confused', 'emoticons')
    appAddPictogramType('007-wink', 'emoticons', {isPermanentSticky = true})
    appAddPictogramType('004-laughing', 'emoticons', {isPermanentSticky = true})
    appAddPictogramType('005-angry', 'emoticons', {isEmoticon = true})
    appAddPictogramType('006-tongue', 'emoticons', {isEmoticon = true})
    appAddPictogramType('008-shock', 'emoticons', {isEmoticon = true})
    appAddPictogramType('009-neutral', 'emoticons', {isEmoticon = true})
    appAddPictogramType('010-in-love', 'emoticons', {isEmoticon = true})
    appAddPictogramType('011-mild-surprise', 'emoticons', {isEmoticon = true})
    appAddPictogramType('012-sad', 'emoticons', {isEmoticon = true})
    appAddPictogramType('013-drunk-or-sleeping', 'emoticons', {isEmoticon = true})
    appAddPictogramType('014-glasses', 'emoticons', {isEmoticon = true})
    appAddPictogramType('015-cool', 'emoticons', {isEmoticon = true})
    appAddPictogramType('016-money', 'emoticons', {isEmoticon = true})
    appAddPictogramType('017-not-love', 'emoticons', {isEmoticon = true})
    appAddPictogramType('018-undecided', 'emoticons', {isEmoticon = true})
    appAddPictogramType('019-different-smile', 'emoticons', {isEmoticon = true})
    appAddPictogramType('020-blushing', 'emoticons', {isEmoticon = true})
    appAddPictogramType('021-evil', 'emoticons', {isEmoticon = true})
    appAddPictogramType('022-odd', 'emoticons', {isEmoticon = true})
    appAddPictogramType('023-angel', 'emoticons', {isEmoticon = true})
    appAddPictogramType('024-love-eyes', 'emoticons', {isEmoticon = true})
    appAddPictogramType('025-vampire-teeth', 'emoticons', {isEmoticon = true})
    appAddPictogramType('026-very-happy', 'emoticons', {isEmoticon = true})
    appAddPictogramType('027-angry-shout', 'emoticons', {isEmoticon = true})
    appAddPictogramType('028-big-surprise', 'emoticons', {isEmoticon = true})
    appAddPictogramType('029-mild-smile', 'emoticons', {isEmoticon = true})
    appAddPictogramType('030-licking', 'emoticons', {isEmoticon = true})
    appAddPictogramType('031-teeth', 'emoticons', {isEmoticon = true})
    appAddPictogramType('032-angry', 'emoticons', {isEmoticon = true})
    appAddPictogramType('033-thumbs-up', 'emoticons', {isPermanentSticky = true, isEmoticon = true})
    appAddPictogramType('034-thumbs-down', 'emoticons', {isPermanentSticky = true, isEmoticon = true})
    appAddPictogramType('035-hmm', 'emoticons', {isEmoticon = true})
    appAddPictogramType('waving-hi', 'emoticons')
    appAddPictogramType('036-cheering', 'emoticons')
    appAddPictogramType('037-folded-hands', 'emoticons')
    appAddPictogramType('038-not-listening', 'emoticons')
    appAddPictogramType('039-not-listening', 'emoticons')
    appAddPictogramType('040-not-speaking', 'emoticons')
    appAddPictogramType('041-down', 'emoticons')
    appAddPictogramType('042-sneaking', 'emoticons')
    appAddPictogramType('043-there-there', 'emoticons')
    appAddPictogramType('044-no-thanks', 'emoticons')
    appAddPictogramType('045-shrugging', 'emoticons')
    appAddPictogramType('046-me-me', 'emoticons')
    appAddPictogramType('047-crying', 'emoticons')
    appAddPictogramType('048-cheers', 'emoticons')
    appAddPictogramType('049-hey', 'emoticons')
    appAddPictogramType('050-bowing', 'emoticons')
    appAddPictogramType('051-fear', 'emoticons', {isEmoticon = true})
    appAddPictogramType('052-high', 'emoticons', {isEmoticon = true})
    appAddPictogramType('053-enlightened', 'emoticons', {isEmoticon = true})
    appAddPictogramType('054-shocked', 'emoticons', {isEmoticon = true})
    appAddPictogramType('055', 'emoticons', {isEmoticon = true})
    appAddPictogramType('056', 'emoticons')
    appAddPictogramType('057', 'emoticons')
    appAddPictogramType('058', 'emoticons')
    appAddPictogramType('059', 'emoticons')
    appAddPictogramType('060', 'emoticons', {isEmoticon = true})
    appAddPictogramType('061', 'emoticons')
    appAddPictogramType('062', 'emoticons')
    appAddPictogramType('063', 'emoticons')
    appAddPictogramType('064', 'emoticons')
    appAddPictogramType('065', 'emoticons', {isEmoticon = true})
    appAddPictogramType('066', 'emoticons', {isEmoticon = true})
    appAddPictogramType('067', 'emoticons')
    appAddPictogramType('068', 'emoticons', {isEmoticon = true})
    appAddPictogramType('069', 'emoticons')
    appAddPictogramType('070', 'emoticons', {isEmoticon = true})
    appAddPictogramType('071', 'emoticons')
    appAddPictogramType('072', 'emoticons', {isEmoticon = true})
    appAddPictogramType('073', 'emoticons')
    appAddPictogramType('074', 'emoticons')
    appAddPictogramType('075', 'emoticons', {isEmoticon = true})
    appAddPictogramType('076', 'emoticons')
    appAddPictogramType('077', 'emoticons', {isEmoticon = true})
    appAddPictogramType('078', 'emoticons')
    appAddPictogramType('079', 'emoticons')
    appAddPictogramType('080', 'emoticons')
    appAddPictogramType('081', 'emoticons')
    appAddPictogramType('082', 'emoticons', {isEmoticon = true})
    appAddPictogramType('083', 'emoticons')
    appAddPictogramType('084', 'emoticons')
    appAddPictogramType('085', 'emoticons')
    appAddPictogramType('086', 'emoticons')
    appAddPictogramType('087', 'emoticons')
    appAddPictogramType('088', 'emoticons')
    appAddPictogramType('089', 'emoticons')
    appAddPictogramType('090', 'emoticons')
    appAddPictogramType('091', 'emoticons')
    appAddPictogramType('142-long-nose', 'emoticons')
    appAddPictogramType('144-one-eye', 'emoticons')
    appAddPictogramType('145-big-mouth', 'emoticons')
    appAddPictogramType('146-mouthless', 'emoticons')
    appAddPictogramType('147-eyeless', 'emoticons')

    appAddPictogramType('021-dice', 'things')
    appAddPictogramType('022-socks', 'things')
    appAddPictogramType('023-shoes', 'things')
    appAddPictogramType('024-shirt', 'things')
    appAddPictogramType('025-pullover', 'things')
    appAddPictogramType('026-jeans', 'things')
    appAddPictogramType('027-tie', 'things')
    appAddPictogramType('028-hat', 'things')
    appAddPictogramType('029-glasses', 'things')
    appAddPictogramType('031-saw', 'things')
    appAddPictogramType('032-hammer', 'things')
    appAddPictogramType('033-shovel', 'things')
    appAddPictogramType('034-nail', 'things')
    appAddPictogramType('035-frame', 'things')
    appAddPictogramType('036-window', 'things')
    appAddPictogramType('040-lamp', 'things')
    appAddPictogramType('041-light-bulb', 'things')
    appAddPictogramType('054-paper', 'things')

    appAddPictogramType('096-meat', 'things')
    appAddPictogramType('097-hamburger', 'things')
    appAddPictogramType('098-fries', 'things')
    appAddPictogramType('099-rice', 'things')
    appAddPictogramType('100-noodles', 'things')
    appAddPictogramType('101-bowl', 'things')
    appAddPictogramType('102-chopsticks', 'things')
    appAddPictogramType('103-plate', 'things')
    appAddPictogramType('104-fork', 'things')
    appAddPictogramType('105-knife', 'things')
    appAddPictogramType('106-spoon', 'things')
    appAddPictogramType('107-restaurant', 'things')
    appAddPictogramType('108-table', 'things')
    appAddPictogramType('016-chair', 'things')
    appAddPictogramType('109-glass', 'things')
    appAddPictogramType('111-mug', 'things')
    appAddPictogramType('129-beer', 'things')
    appAddPictogramType('136-dinner', 'things')
    appAddPictogramType('110-drinking-straw', 'things')
    appAddPictogramType('130-cocktail', 'things')
    appAddPictogramType('131-tea', 'things')
    appAddPictogramType('132-coffee', 'things')
    appAddPictogramType('112-wine-glass', 'things')
    appAddPictogramType('113-bottle', 'things')
    appAddPictogramType('bottle', 'things')
    appAddPictogramType('135-cheers', 'things')

    appAddPictogramType('114-can', 'things')
    appAddPictogramType('116-tasty', 'things')
    appAddPictogramType('117-yucky', 'things')
    appAddPictogramType('118-disgusting', 'things')
    appAddPictogramType('119-apple', 'things')
    appAddPictogramType('120-banana', 'things')
    appAddPictogramType('121-pineapple', 'things')
    appAddPictogramType('122-grows-on-trees', 'things')
    appAddPictogramType('123-grapes', 'things')
    appAddPictogramType('124-pot', 'things')
    appAddPictogramType('125-ice-cubes', 'things')
    appAddPictogramType('126-spicy', 'things')
    appAddPictogramType('127-salt', 'things')
    appAddPictogramType('128-pepper', 'things')
    appAddPictogramType('133-salad', 'things')
    appAddPictogramType('134-soup', 'things')
    appAddPictogramType('137-hot-dog', 'things')
    appAddPictogramType('138-tooth-picks', 'things')
    appAddPictogramType('139-dirt', 'things')

    appAddPictogramType('001-computer', 'things')
    appAddPictogramType('002-tablet-computer', 'things')
    appAddPictogramType('003-computer-mouse', 'things')
    appAddPictogramType('004-keyboard', 'things')
    appAddPictogramType('005-tv', 'things')
    appAddPictogramType('052-mobile-phone', 'things')
    appAddPictogramType('053-phone', 'things')
    appAddPictogramType('055-screen', 'things')
    appAddPictogramType('056-cable', 'things')

    appAddPictogramType('006-book', 'things')
    appAddPictogramType('007-comic-book', 'things')
    appAddPictogramType('008-magazine', 'things')
    appAddPictogramType('019-pencil', 'things')
    appAddPictogramType('009-lighter', 'things')
    appAddPictogramType('010-cigarette', 'things')
    appAddPictogramType('030-pipe', 'things')
    appAddPictogramType('011-spray', 'things')
    appAddPictogramType('012-toothbrush', 'things')
    appAddPictogramType('013-water-tap', 'things')
    appAddPictogramType('014-toilet', 'things')
    appAddPictogramType('017-couch', 'things')
    appAddPictogramType('018-carpet', 'things')

    appAddPictogramType('037-ring', 'things')
    appAddPictogramType('038-jacket', 'things')
    appAddPictogramType('039-gloves', 'things')
    appAddPictogramType('042-underwear', 'things')
    appAddPictogramType('043-panties', 'things')
    appAddPictogramType('044-bra', 'things')
    appAddPictogramType('045-swimsuit', 'things')
    appAddPictogramType('046-tissue', 'things')
    appAddPictogramType('047-skirt', 'things')
    appAddPictogramType('048-boots', 'things')
    appAddPictogramType('049-high-heels', 'things')
    appAddPictogramType('050-button', 'things')
    appAddPictogramType('051-soap', 'things')
    appAddPictogramType('072-pacifier', 'things')

    appAddPictogramType('057-antenna', 'things')
    appAddPictogramType('058-cushion', 'things')
    appAddPictogramType('059-leg', 'things')
    appAddPictogramType('time', 'things')
    appAddPictogramType('060-button', 'things')
    appAddPictogramType('061-power-socket', 'things')
    appAddPictogramType('062-power-plug', 'things')
    appAddPictogramType('063-electricity', 'things')
    appAddPictogramType('064-poison', 'things')
    appAddPictogramType('065-bomb', 'things')
    appAddPictogramType('066-explosion', 'things')
    appAddPictogramType('067-microscope', 'things')
    appAddPictogramType('068-telescope', 'things')
    appAddPictogramType('069-skeleton', 'things')
    appAddPictogramType('070-bone', 'things')
    appAddPictogramType('071-blood', 'things')

    appAddPictogramType('073-tennis-racket', 'things')
    appAddPictogramType('074-tennis-ball', 'things')
    appAddPictogramType('075-football', 'things')
    appAddPictogramType('076-american-football', 'things')
    appAddPictogramType('077-hockey-racket', 'things')
    appAddPictogramType('078-table-tennis-racket', 'things')
    appAddPictogramType('079-net', 'things')
    appAddPictogramType('080-ball', 'things')
    appAddPictogramType('081-necklace', 'things')
    appAddPictogramType('082-bow-tie', 'things')
    appAddPictogramType('083-watch', 'things')

    appAddPictogramType('140-trashcan', 'things')
    appAddPictogramType('141-chat', 'things')
    appAddPictogramType('142-who', 'things')
    appAddPictogramType('143-safe', 'things')
    appAddPictogramType('144-gun', 'things')
    appAddPictogramType('145-wheel', 'things')
    appAddPictogramType('146-news', 'things')
    appAddPictogramType('147-stairs', 'things')
    appAddPictogramType('148-flag', 'things')
    appAddPictogramType('149-footprints', 'things')
    appAddPictogramType('150-wise-master', 'things')
    appAddPictogramType('152-password', 'things')
    appAddPictogramType('153-key', 'things')
    appAddPictogramType('154-parachute', 'things')
    appAddPictogramType('155-mask', 'things')
    appAddPictogramType('156-seatbelt', 'things')
    appAddPictogramType('157-puppet', 'things')
    appAddPictogramType('158-leash', 'things')
    appAddPictogramType('159-funnel', 'things')
    appAddPictogramType('160-hose', 'things')
    appAddPictogramType('161-king', 'things')
    appAddPictogramType('162-filter', 'things')
    appAddPictogramType('163-candy', 'things')
    appAddPictogramType('164-toilet-paper', 'things')
    appAddPictogramType('165-sign', 'things')
    appAddPictogramType('166-cable', 'things')
    appAddPictogramType('167-broken-cable', 'things')
    appAddPictogramType('167-machine', 'things')
    appAddPictogramType('168-box', 'things')
    appAddPictogramType('001-train', 'location')
    appAddPictogramType('002-car', 'location')
    appAddPictogramType('003-bus', 'location')
    appAddPictogramType('004-bus', 'location')
    appAddPictogramType('005-motorbike', 'location')
    appAddPictogramType('006-airplane', 'location')
    appAddPictogramType('007-ship', 'location')
    appAddPictogramType('008-skateboard', 'location')
    appAddPictogramType('009-rollerblades', 'location')
    appAddPictogramType('010-by-foot', 'location')
    appAddPictogramType('011-mountains', 'location')
    appAddPictogramType('012-ocean', 'location')
    appAddPictogramType('013-island', 'location')
    appAddPictogramType('014-city', 'location')
    appAddPictogramType('015-village', 'location')
    appAddPictogramType('016-house', 'location')
    appAddPictogramType('017-living-room', 'location')
    appAddPictogramType('018-bed-room', 'location')
    appAddPictogramType('019-sun', 'location')
    appAddPictogramType('020-cloud', 'location')
    appAddPictogramType('021-rain', 'location')
    appAddPictogramType('022-sky', 'location')
    appAddPictogramType('023-tree', 'location')
    appAddPictogramType('024-flower', 'location')
    appAddPictogramType('025-fire', 'location')
    appAddPictogramType('026-water', 'location')
    appAddPictogramType('027-air', 'location')
    appAddPictogramType('028-sign', 'location')
    appAddPictogramType('029-rock', 'location')
    appAddPictogramType('030-road', 'location')
    appAddPictogramType('031-skyscraper', 'location')
    appAddPictogramType('032-door', 'location')
    appAddPictogramType('033-cinema', 'location')
    appAddPictogramType('033-traffic-light', 'location')
    appAddPictogramType('034-internet', 'location')
    appAddPictogramType('054-bridge', 'location')
    appAddPictogramType('055-bus-stop', 'location')
    appAddPictogramType('107-information', 'location')
    appAddPictogramType('056-cave', 'location')
    appAddPictogramType('057-grass', 'location')
    appAddPictogramType('060-earth', 'location')
    appAddPictogramType('061-planet', 'location')
    appAddPictogramType('083-birds', 'location')
    appAddPictogramType('084-cat', 'location')
    appAddPictogramType('085-mouse', 'location')
    appAddPictogramType('086-duck', 'location')
    appAddPictogramType('087-duckling', 'location')
    appAddPictogramType('088-monster', 'location')
    appAddPictogramType('089-horse', 'location')
    appAddPictogramType('090-sheep', 'location')
    appAddPictogramType('091-pig', 'location')
    appAddPictogramType('092-unicorn', 'location')
    appAddPictogramType('093-chicken', 'location')
    appAddPictogramType('094-caveman', 'location')
    appAddPictogramType('095-prehistoric-animal', 'location')
    appAddPictogramType('096-alien', 'location')
    appAddPictogramType('097-robot', 'location')
    appAddPictogramType('098-insect', 'location')
    appAddPictogramType('099-map', 'location')
    appAddPictogramType('100-elephant', 'location')
    appAddPictogramType('101-fly', 'location')
    appAddPictogramType('102-dinosaur', 'location')
    appAddPictogramType('103-spider', 'location')
    appAddPictogramType('104-cobweb', 'location')
    appAddPictogramType('105-bear', 'location')
    appAddPictogramType('106-ant', 'location')
    appAddPictogramType('108-lion', 'location')
    appAddPictogramType('109-bull', 'location')
    appAddPictogramType('110-snake', 'location')
    appAddPictogramType('111-ostrich', 'location')
    appAddPictogramType('112-space-ship', 'location')
    appAddPictogramType('113-moon', 'location')
    appAddPictogramType('114-b-planet', 'location')
    appAddPictogramType('114-earth', 'location')
    appAddPictogramType('115-stars', 'location')
    appAddPictogramType('116-desert', 'location')
    appAddPictogramType('117-lonely-place', 'location')
    appAddPictogramType('118-crowded-place', 'location')

    appAddPictogramType('020-a-1', 'shapes')
    appAddPictogramType('020-b-2', 'shapes')
    appAddPictogramType('020', 'shapes')
    appAddPictogramType('021', 'shapes')
    appAddPictogramType('022', 'shapes')
    appAddPictogramType('023', 'shapes')
    appAddPictogramType('024', 'shapes')
    appAddPictogramType('025', 'shapes')
    appAddPictogramType('026', 'shapes')
    appAddPictogramType('027', 'shapes')
    appAddPictogramType('028', 'shapes')
    appAddPictogramType('029', 'shapes')
    appAddPictogramType('030', 'shapes')
    appAddPictogramType('031', 'shapes')
    appAddPictogramType('032', 'shapes')
    appAddPictogramType('033', 'shapes')
    appAddPictogramType('034', 'shapes')
    appAddPictogramType('035', 'shapes')
    appAddPictogramType('left-pointer', 'shapes')
    appAddPictogramType('right-pointer', 'shapes')
    appAddPictogramType('left-right-pointer', 'shapes')
    appAddPictogramType('036', 'shapes')
    appAddPictogramType('037', 'shapes')
    appAddPictogramType('038', 'shapes')
    appAddPictogramType('039', 'shapes')
    appAddPictogramType('040', 'shapes')
    appAddPictogramType('041', 'shapes')
    appAddPictogramType('042', 'shapes')
    appAddPictogramType('043', 'shapes')
    appAddPictogramType('044', 'shapes')
    appAddPictogramType('045', 'shapes')
    appAddPictogramType('046', 'shapes')
    appAddPictogramType('047', 'shapes')
    appAddPictogramType('048', 'shapes')
    appAddPictogramType('049', 'shapes')
    appAddPictogramType('050-on-target', 'shapes')
    appAddPictogramType('051-off-target', 'shapes')
    appAddPictogramType('052-reflective-surface', 'shapes')
    appAddPictogramType('053-non-reflective-surface', 'shapes')
    appAddPictogramType('054', 'shapes')
    appAddPictogramType('055', 'shapes')
    appAddPictogramType('056', 'shapes')
    appAddPictogramType('057', 'shapes')
    appAddPictogramType('058', 'shapes')
    appAddPictogramType('059', 'shapes')
    appAddPictogramType('060', 'shapes')
    appAddPictogramType('061', 'shapes')
    appAddPictogramType('062', 'shapes')
    appAddPictogramType('063', 'shapes')
    appAddPictogramType('064', 'shapes')
    appAddPictogramType('065', 'shapes')
    appAddPictogramType('066', 'shapes')
    appAddPictogramType('067', 'shapes')
    appAddPictogramType('068', 'shapes')
    appAddPictogramType('069', 'shapes')
    appAddPictogramType('070', 'shapes')
    appAddPictogramType('071', 'shapes')
    appAddPictogramType('072', 'shapes')
    appAddPictogramType('073', 'shapes')
    appAddPictogramType('074', 'shapes')
    appAddPictogramType('075', 'shapes')
    appAddPictogramType('077', 'shapes')
    appAddPictogramType('078', 'shapes')
    appAddPictogramType('079', 'shapes')
    appAddPictogramType('080', 'shapes')
    appAddPictogramType('081', 'shapes')
    appAddPictogramType('082', 'shapes')
    appAddPictogramType('083', 'shapes')
    appAddPictogramType('084', 'shapes')
    appAddPictogramType('085', 'shapes')
    appAddPictogramType('086', 'shapes')
    appAddPictogramType('087', 'shapes')
    appAddPictogramType('088', 'shapes')
    appAddPictogramType('089', 'shapes')
    appAddPictogramType('090', 'shapes')
    appAddPictogramType('091', 'shapes')
    appAddPictogramType('092', 'shapes')
    appAddPictogramType('093', 'shapes')
    appAddPictogramType('094', 'shapes')
    appAddPictogramType('095', 'shapes')
    appAddPictogramType('098', 'shapes')
    appAddPictogramType('099', 'shapes')
    appAddPictogramType('097', 'shapes')
    appAddPictogramType('100', 'shapes')
    appAddPictogramType('101', 'shapes')
    appAddPictogramType('102-money', 'shapes')
    appAddPictogramType('105', 'shapes')
    appAddPictogramType('106', 'shapes')
    appAddPictogramType('107', 'shapes')
    appAddPictogramType('108-letters', 'shapes')
    appAddPictogramType('109-numbers', 'shapes')
    appAddPictogramType('112-death', 'shapes')
    appAddPictogramType('113-line', 'shapes')
    appAddPictogramType('114-shapes', 'shapes')
    appAddPictogramType('115-up', 'shapes')
    appAddPictogramType('116-down', 'shapes')
    appAddPictogramType('117', 'shapes')
    appAddPictogramType('118', 'shapes')
    appAddPictogramType('122-1', 'shapes')
    appAddPictogramType('123-2', 'shapes')
    appAddPictogramType('124-3', 'shapes')
    appAddPictogramType('125-4', 'shapes')
    appAddPictogramType('126-5', 'shapes')
    appAddPictogramType('127-6', 'shapes')
    appAddPictogramType('128-7', 'shapes')
    appAddPictogramType('129-8', 'shapes')
    appAddPictogramType('130-9', 'shapes')
    appAddPictogramType('131-0', 'shapes')
    appAddPictogramType('132-many', 'shapes')
    appAddPictogramType('133-network', 'shapes')
    appAddPictogramType('134-attack-1', 'shapes')
    appAddPictogramType('135-attack-2', 'shapes')
    appAddPictogramType('138-here', 'shapes')
    appAddPictogramType('150-first', 'shapes')
    appAddPictogramType('151-second', 'shapes')
    appAddPictogramType('152-previous-back', 'shapes')
    appAddPictogramType('153-next', 'shapes')
    appAddPictogramType('154-uncommon', 'shapes')
    appAddPictogramType('155-common', 'shapes')
    appAddPictogramType('157-come', 'shapes')
    appAddPictogramType('158-go', 'shapes')
    appAddPictogramType('159-some', 'shapes')
    appAddPictogramType('160-one-specific', 'shapes')
    appAddPictogramType('161-all', 'shapes')
    appAddPictogramType('162-list', 'shapes')

    appAddPictogramType('162-infinity', 'shapes')
    appAddPictogramType('163-many-to-one', 'shapes')
    appAddPictogramType('164-one-to-many', 'shapes')
    appAddPictogramType('165-energy', 'shapes')

    appAddPictogramType('1', 'letters')
    appAddPictogramType('2', 'letters')
    appAddPictogramType('3', 'letters')
    appAddPictogramType('4', 'letters')
    appAddPictogramType('5', 'letters')
    appAddPictogramType('6', 'letters')
    appAddPictogramType('7', 'letters')
    appAddPictogramType('8', 'letters')
    appAddPictogramType('9', 'letters')
    appAddPictogramType('0', 'letters')
    appAddPictogramType('q', 'letters')
    appAddPictogramType('w', 'letters')
    appAddPictogramType('e', 'letters')
    appAddPictogramType('r', 'letters')
    appAddPictogramType('t', 'letters')
    appAddPictogramType( misc.getIf(app.language == 'de', 'z', 'y'), 'letters' )
    appAddPictogramType('u', 'letters')
    appAddPictogramType('i', 'letters')
    appAddPictogramType('o', 'letters')
    appAddPictogramType('p', 'letters')
    appAddPictogramType('a', 'letters')
    appAddPictogramType('s', 'letters')
    appAddPictogramType('d', 'letters')
    appAddPictogramType('f', 'letters')
    appAddPictogramType('g', 'letters')
    appAddPictogramType('h', 'letters')
    appAddPictogramType('j', 'letters')
    appAddPictogramType('k', 'letters')
    appAddPictogramType('l', 'letters')
    appAddPictogramType('accent-roof-a', 'letters')
    appAddPictogramType('accent-forward-e', 'letters')
    appAddPictogramType( misc.getIf(app.language == 'de', 'y', 'z'), 'letters' )
    appAddPictogramType('x', 'letters')
    appAddPictogramType('c', 'letters')
    appAddPictogramType('v', 'letters')
    appAddPictogramType('b', 'letters')
    appAddPictogramType('n', 'letters')
    appAddPictogramType('m', 'letters')
    appAddPictogramType('accent-backward-e', 'letters')
    appAddPictogramType('accent-roof-e', 'letters')
    appAddPictogramType('121', 'letters')
    appAddPictogramType('umlaut-a', 'letters')
    appAddPictogramType('umlaut-o', 'letters')
    appAddPictogramType('umlaut-u', 'letters')
    appAddPictogramType('space', 'letters', {hasAlternateForWriting = true})

    appAddPictogramType('single-apostrophe', 'letters')
    appAddPictogramType('110-and', 'letters')
    appAddPictogramType('111-copyright', 'letters')
    appAddPictogramType('119', 'letters')
    appAddPictogramType('120', 'letters')

    appAddPictogramType('001-dot', 'letters', {isPermanentSticky = true})
    appAddPictogramType('002-exclamation-mark', 'letters', {isPermanentSticky = true, isSentenceEnd = true})
    appAddPictogramType('003-question-mark', 'letters', {isPermanentSticky = true, isSentenceEnd = true})
    appAddPictogramType('004-comma', 'letters', {isPermanentSticky = true})
    appAddPictogramType('005-dots', 'letters', {isPermanentSticky = true, isSentenceEnd = true})
    appAddPictogramType('006-colon', 'letters', {isPermanentSticky = true})
    appAddPictogramType('007-plus', 'letters', {isPermanentSticky = true, isConnector = true})
    appAddPictogramType('103-minus', 'letters')
    appAddPictogramType('008-slash', 'letters', {isPermanentSticky = true})
    appAddPictogramType('009-equal', 'letters', {isPermanentSticky = true})
    appAddPictogramType('104-like', 'letters', {isPermanentSticky = true})
    appAddPictogramType('010-not-equal', 'letters')
    appAddPictogramType('011-check', 'letters', {isPermanentSticky = true})
    appAddPictogramType('012-incorrect', 'letters', {isPermanentSticky = true})
    appAddPictogramType('013-bracket-open', 'letters')
    appAddPictogramType('014-bracket-close', 'letters')
    appAddPictogramType('150-square-bracket-open', 'letters', {isPermanentSticky = true})
    appAddPictogramType('151-square-bracket-close', 'letters', {isPermanentSticky = true})
    appAddPictogramType('apostrophe', 'letters', {isPermanentSticky = true})

    appAddPictogramType('115-candle', 'things')

    --------------------------------------------------------

    appAddPictogramType('090-kick', 'verbs')
    appAddPictogramType('091-playing', 'verbs')

    appAddPictogramType('170-angel', 'things')
    appAddPictogramType('171-business-person', 'things')
    appAddPictogramType('172-game', 'things')
    appAddPictogramType('139-future', 'shapes')
    appAddPictogramType('140-past', 'shapes')
    appAddPictogramType('141-maze', 'shapes')

    appAddPictogramType('143-odd', 'shapes')
    appAddPictogramType('148-wall-between', 'shapes')
    appAddPictogramType('149-multi-eyes', 'shapes')

    appAddPictogramType('text-cursor', 'special')
    app.textCursorIndex = #app.pictogramTypes
end
